--- 
driver: 
  customize: 
    cpus: 2
    memory: 1024
  name: vagrant
  network: 
    - 
      - forwarded_port
      - 
        auto_correct: true
        guest: 8080
        host: 9090
platforms: 
  - 
    name: ubuntu-14.04
    run_list: 
      - "apt::default"
      - "jenkins::java"
provisioner: 
  name: chef_zero
suites: 
  - 
    attributes: 
      jenkins: 
        master: 
          install_method: package
    name: default
    run_list: 
      - "recipe[jenkins::master]"

